### ISSUE TITLE
Issue with data from 2024-06-01

### ISSUE THREAD

**Issue by StefanoCandiani** [explorerjs32/rho_data_reduction_pipeline#11]
I was experimenting with the logging and found that, at least my computer, wasn't able to process the 2024-06-01 file to its entirety. It was able to get through the master flats and then it stopped working with the following errors produced: 

```
python/site-packages/numpy/core/fromnumeric.py:3504: RuntimeWarning: Mean of empty slice. return _methods._mean(a, axis=axis, dtype=dtype,
python/site-packages/numpy/core/_methods.py:129: RuntimeWarning: invalid value encountered in scalar divide ret = ret.dtype.type(ret / rcount) 
```

Don't really know what could be causing this... anyone know?

**Comment by explorerjs32** [comment]
I believe this issue might've been caused by the the fact that the 2024-06-01 data directory contains only calibration frames and no light frames at all. This might cause the masking of light frames in the data reduction function to return an empty data frame and therefore the data arrays would be empty. If you run the code including both the 2024-05-30 and 2024-06-01 you shouldn't have any issues
